apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-298817
  artifacts:
    - image: eu.gcr.io/ticketing-dev-298817/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "***/*.ts"
            dest: .
    - image: eu.gcr.io/ticketing-dev-298817/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: eu.gcr.io/ticketing-dev-298817/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: eu.gcr.io/ticketing-dev-298817/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: eu.gcr.io/ticketing-dev-298817/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: eu.gcr.io/ticketing-dev-298817/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
